DROP TABLE IF EXISTS album_artist CASCADE;
DROP TABLE IF EXISTS playlist_track CASCADE;
DROP TABLE IF EXISTS track_artist CASCADE;

DROP TABLE IF EXISTS album CASCADE;
DROP TABLE IF EXISTS artist CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS playlist CASCADE;
DROP TABLE IF EXISTS track CASCADE;
DROP TABLE IF EXISTS user_ CASCADE;
